### ISSUE TITLE
can not load dicom file

### ISSUE THREAD

**Issue by cat2tom** [tomdoel/pulmonarytoolkit#20]
Thanks for developing this fantastic tool. When I load lung Dicom data, it popped up a message box saying 'No appropriate method, property or field 'GetKey for class PTKPluginResultsInfo'. 

could you help me resolve this issue? 

In addition, could you put some test data for the user to test?

**Comment by tomdoel** [comment]
Hi,

Thanks for reporting this problem. I confirm this is a bug which should be fixed in version 0.7.5 which will be released very soon.

I have added a SampleData page to the wiki which includes links to available data. I will add more links when I find them. Unfortunately I don't have permission to share any of the data I am using.

Thanks

**Comment by tomdoel** [comment]
Closing this issue as I believe it is fixed in the current version (0.7.6)
