### ISSUE TITLE
Deleting multiple patients

### ISSUE THREAD

**Issue by jakublaznovsky** [tomdoel/pulmonarytoolkit#40]
Hello, 
thanks for developing Pulmonary Toolkit.
Maybe, I just did something wrong while importing the data, but every single slice from the measurement imported as an individual patient. So the result is about 200 imported patients in patient browser. Is there any possibility how to delete multiple patients in one operation? Or an option to reset all settings of PTK? 
Thank you in advance.

**Comment by tomdoel** [comment]
Hi,

One common reason this can happen is if the Patient ID tag has been removed, or is not the same for each slice - these most likely occur due to an anonymisation process not being correctly configured. PTK needs the Patient ID to be present and the same on each slice. If thats not the case the tags can be added or corrected using a Dicom edit tool eg  Horos or DicomBrowser. You would then need to delete the datasets from PTK and re-import them.

**To delete multiple patients**:
You can use the API to delete multiple patients by deleting each series for each patient. The `DeleteDatasets()` call on a PTKMain() object takes in a cell array which are the series uids to delete. For example the following script will delete every patient and every series:

```
ptk_main = PTKMain();

% Delete all series for all subjects
all_uids = ptk_main.FrameworkAppDef.GetFrameworkDirectories().GetUidsOfAllDatasetsInCache();
ptk_main.DeleteDatasets(all_uids); 
```

**To completely reset PTK and delete all your imported data, edits and results**:
- Close Matlab
- (Backup, if you want) and then delete the `TDPulmonaryToolkit` folder in your home directory (Warning: this will delete all your imported data, all results, all manual segmentations, all markers, etc)

**Keyboard Shortcut for deleting a single series**:
The Delete key will delete the currently loaded series

**Comment by jakublaznovsky** [comment]
Hello Tom,
Thank you for an exhaustive answer. You are right that I've imported badly anonymised Dicom data. Whole patients database was deleted via your code, Dicom data was properly configured, and everything works perfectly! Thanks

**Comment by tomdoel** [comment]
Thank you for your comments. I'm glad everything is working!
